services:
  web:
    build: .
    image: hochschule-web
    ports:
      - "8090:80"
    restart: unless-stopped

  whoami:
    image: traefik/whoami
    ports:
      - "8091:80"
    restart: unless-stopped
